# Generated by Django 4.1.3 on 2022-12-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='customer',
        ),
    ]
