# Generated by Django 4.1.3 on 2022-12-07 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_prodetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodetails',
            name='quantity',
        ),
    ]
